apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
  labels:
    io.kompose.service: unifi-lb
  name: unifi-lb
  namespace: unifi
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8843"
      port: 8843
      targetPort: 8843
    - name: "8880"
      port: 8880
      targetPort: 8880
    - name: "6789"
      port: 6789
      targetPort: 6789
  selector:
    io.kompose.service: unifi-controller
  type: LoadBalancer
  loadBalancerIP: 10.250.0.211
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
  labels:
    io.kompose.service: unifi-lb-udp
  name: unifi-lb-udp
  namespace: unifi
spec:
  ports:
    - name: "1900"
      port: 1900
      protocol: UDP
      targetPort: 1900
    - name: "3478"
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: "5514"
      port: 5514
      protocol: UDP
      targetPort: 5514
    - name: "10001"
      port: 10001
      protocol: UDP
      targetPort: 10001
  selector:
    io.kompose.service: unifi-controller
  type: LoadBalancer
  loadBalancerIP: 10.250.0.211

