---
name: Kubernetes Deploy

on:
  push:
    branches:
      - main

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Unifi App Namespace
        uses: actions-hub/kubectl@master
        with:
          args: apply -f unifi-namespace.yaml

      - name: Deploy Unifi App Volume
        uses: actions-hub/kubectl@master
        with:
          args: apply -f unifi-pv.yaml

      - name: Deploy Unifi App Volume Claim
        uses: actions-hub/kubectl@master
        with:
          args: apply -f unifi-pvc.yaml

      - name: Deploy Unifi App Load Balancer Service
        uses: actions-hub/kubectl@master
        with:
          args: apply -f unifi-lb-service.yaml

      - name: Deploy Unifi App Deployment
        uses: actions-hub/kubectl@master
        with:
          args: apply -f unifi-deployment.yaml
...
